spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
    active: test

  application:
    name: asignaturas-servicio
  config:
    import: optional:configserver:http://localhost:8888





eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka


server:
  port: 8081
  # Definir el puerto del microservicio
  # Esto es útil para levantar múltiples instancias sin conflictos de puerto.

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

info:
  app:
    name: Asignaturas Microservicio
    version: 1.0.0
