spring:
  application:
    name: matriculas-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

microservicios:
  token-jwt: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTEwMjE0NywiZXhwIjoxNzQ1MTg4NTQ3fQ.AfaWsu-Cuza-RHUjxQYsj7D5yRcwZLkJHkbfbLLqiuI


management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info, prometheus
  endpoint:
    health:
      show-details: always


info:
  app:
    name: Matriculas Microservicio
    version: 1.0.0
