name: Maven CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Config Server
        run: mvn clean package -DskipTests --file config-server/pom.xml

      - name: Build Eureka Server
        run: mvn clean package -DskipTests --file eureka-server/pom.xml

      - name: Build Usuarios Servicio
        run: mvn clean package -DskipTests --file usuarios-servicio/pom.xml

      - name: Build Asignaturas Servicio
        run: mvn clean package -DskipTests --file asignaturas-servicio/pom.xml

      - name: Start Config Server
        run: nohup java -jar config-server/target/config-server-0.0.1-SNAPSHOT.jar > config.log 2>&1 &

      - name: Wait for Config Server
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8888/actuator/health | grep UP; then
              echo " Config Server is up!"
              break
            fi
            echo " Waiting for Config Server..."
            sleep 5
          done

      - name: Start Eureka Server
        run: nohup java -jar eureka-server/target/eureka-server-0.0.1-SNAPSHOT.jar > eureka.log 2>&1 &

      - name: Wait for Eureka Server
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8761/eureka/; then
              echo " Eureka is up!"
              break
            fi
            echo " Waiting for Eureka Server..."
            sleep 5
          done

      - name: Start Usuarios Servicio
        run: nohup java -jar usuarios-servicio/target/usuarios-servicio-0.0.1-SNAPSHOT.jar > usuarios.log 2>&1 &

      - name: Wait for Usuarios Servicio
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8081/actuator/health | grep UP; then
              echo " Usuarios Servicio is up!"
              break
            fi
            echo " Waiting for Usuarios Servicio..."
            sleep 5
          done

      - name: Start Asignaturas Servicio
        run: nohup java -jar asignaturas-servicio/target/asignaturas-servicio-0.0.1-SNAPSHOT.jar > asignaturas.log 2>&1 &

      - name: Wait for Asignaturas Servicio
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8082/actuator/health | grep UP; then
              echo " Asignaturas Servicio is up!"
              break
            fi
            echo " Waiting for Asignaturas Servicio..."
            sleep 5
          done



      - name: Build and Test Matriculas Servicio
        run: mvn clean install --file matriculas-servicio/pom.xml
