name: Maven CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [usuarios-servicio, asignaturas-servicio, matriculas-servicio]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Eureka Server
        run: |
          cd eureka-server
          mvn clean package
          cd ..

      - name: Start Eureka Server
        run: |
          nohup java -jar eureka-server/target/eureka-server-0.0.1-SNAPSHOT.jar > eureka.log 2>&1 &

      - name: Wait for Eureka to start
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:8761/eureka/; then
              echo "Eureka is up!"
              break
            fi
            echo "Waiting for Eureka..."
            sleep 5
          done
          if ! curl -s http://localhost:8761/eureka/; then
            echo "Eureka failed to start"
            cat eureka.log
            exit 1
          fi

      - name: Build and Test ${{ matrix.service }}
        working-directory: ${{ matrix.service }}
        run: mvn clean install
