name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Start Eureka Server
        run: |
          # Inicia el servidor Eureka en segundo plano (puede ser un servicio externo o uno local)
          nohup java -jar /path/to/eureka-server.jar &

      - name: Wait for Eureka to start
        run: |
          # Espera a que el servidor Eureka esté disponible
          until curl -s http://localhost:8761/eureka/; do
            echo "Esperando Eureka..."
            sleep 5
          done

      - name: Build and run the application
        run: |
          mvn clean install

      - name: Run integration tests
        run: |
          mvn test

      - name: Shut down Eureka server
        run: |
          # Detén el servidor Eureka al finalizar las pruebas
          pkill -f eureka-server.jar
